### ISSUE TITLE
Uncaught TypeError: Cannot read property 'sort' of undefined

### ISSUE THREAD

**Issue by pascalchevrel** [Ziink/atom-nav-panel#1]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.3.0-beta5
**System**: Ubuntu 15.10
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package, v0.0.5

### Stack Trace

Uncaught TypeError: Cannot read property 'sort' of undefined

```
At /home/pascalc/.atom/packages/nav-panel/lib/nav-view.coffee:55

TypeError: Cannot read property 'sort' of undefined
    at HTMLDivElement.<anonymous> (/home/pascalc/.atom/packages/nav-panel/lib/nav-view.coffee:55:22)
    at HTMLDivElement.jQuery.event.dispatch (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/usr/share/atom-beta/resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
     -2:23.8.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -2:23.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -2:23.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:39.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -1:39.2.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -1:38.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:54.5.0 core:select-all (atom-text-editor.editor.mini.is-focused)
     -0:52.4.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:50.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:16.3.0 editor:move-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
     -0:15.8.0 editor:select-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
 10x -0:15.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:14.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "slack-ui",
      "code-dark-syntax"
    ],
    "disabledPackages": [
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-ruby",
      "language-ruby-on-rails",
      "metrics",
      "php-integrator-base",
      "php-integrator-autocomplete-plus",
      "php-integrator-annotations",
      "php-integrator-navigation",
      "php-integrator-tooltips",
      "php-composer-completion",
      "atom-autocomplete-php",
      "atom-php-navigation",
      "autocomplete-php",
      "php-analyser",
      "php-class-tree",
      "php-extract-method",
      "php-fmt",
      "php-introspector",
      "tasks",
      "terminal-plus",
      "project-dropdown",
      "imdone-atom",
      "imdone-atom-github"
    ],
    "ignoredNames": [
      ".git",
      "vendor",
      ".svn",
      ".hg",
      ".idea"
    ],
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.3.0
aligner, v0.17.2
aligner-php, v1.0.0
atom-beautify, v0.28.19
atoum-plugin, v0.4.1
autoclose-html, v0.19.0
code-dark-syntax, v0.2.0
color-picker, v2.0.13
docblockr, v0.7.3
dotlang-grammar, v0.0.1
file-icons, v1.6.12
file-type-icons, v0.7.4
gtk-dark-theme, v0.1.4
hidpi, v0.7.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
inline-messenger, v1.2.8
keyboard-localization, v1.4.10
language-htaccess, v0.1.1
linter, v1.11.2
linter-php, v1.1.4
minimap, v4.16.1
nav-panel, v0.0.5
php-cs-fixer, v2.5.1
php-twig, v4.0.0
pigments, v0.19.0
project-manager, v2.6.5
quick-docs, v0.1.0
save-session, v0.15.7
silverstripe-syntax-and-snippets, v0.4.0
slack-ui, v0.5.0
symbols-tree-view, v0.10.1

# Dev
No dev packages
```

**Comment by Ziink** [comment]
Fixed in v0.0.6
