### ISSUE TITLE
Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined

### ISSUE THREAD

**Issue by Envo** [Ziink/atom-nav-panel#3]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Mac OS X 10.11.1
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package, v0.0.7

### Stack Trace

Uncaught TypeError: Cannot read property 'lastIndexOf' of undefined

```
At /Users/Envo/.atom/packages/nav-panel/lib/nav-parser.coffee:78

TypeError: Cannot read property 'lastIndexOf' of undefined
    at NavParser.module.exports.NavParser.parse (/Users/Envo/.atom/packages/nav-panel/lib/nav-parser.coffee:78:20)
    at NavView.module.exports.NavView.populatePanel (/Users/Envo/.atom/packages/nav-panel/lib/nav-view.coffee:250:21)
    at NavView.module.exports.NavView.setFile (/Users/Envo/.atom/packages/nav-panel/lib/nav-view.coffee:117:6)
    at /Users/Envo/.atom/packages/nav-panel/lib/nav-panel.coffee:65:16
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at stoppedChangingActivePaneItemCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:337:36)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "nucleus-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "symbols-tree-view"
    ]
  },
  "nav-panel": {}
}
```

### Installed Packages

```coffee
# User
atom-beautify, vundefined
color-picker, v2.0.13
file-icons, v1.6.12
language-html5-subtlegradient, v0.1.0
linter, v1.11.2
linter-jshint, v1.2.1
linter-shellcheck, v1.0.2
minimap, v4.16.1
nav-panel, v0.0.7
nucleus-dark-ui, v0.6.12
pigments, v0.19.0

# Dev
No dev packages
```

**Comment by Ziink** [comment]
Fixed in v0.0.8
