### ISSUE TITLE
Uncaught TypeError: Invalid Point: ((185, 0), 0)

### ISSUE THREAD

**Issue by fruwe** [Ziink/atom-nav-panel#32]
[Enter steps to reproduce below:]
1. bookmark a line
2. click on bookmark on the right side

**Atom Version**: 1.10.1
**Electron Version**: 0.37.8
**System**: Mac OS X 10.11.6
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package, v0.0.11
### Stack Trace

Uncaught TypeError: Invalid Point: ((185, 0), 0)

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63

TypeError: Invalid Point: ((185, 0), 0)
    at Function.module.exports.Point.assertValid (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/point.js:63:15)
    at TextBuffer.module.exports.TextBuffer.clipPosition (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1101:13)
    at TextBuffer.module.exports.TextBuffer.clipRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1089:20)
    at DisplayLayer.module.exports.DisplayLayer.destroyFoldsIntersectingBufferRange (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/display-layer.js:325:33)
    at TextEditor.module.exports.TextEditor.unfoldBufferRow (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:2923:32)
    at NavView.module.exports.NavView.gotoMarker (/Users/christian_butzke/.atom/packages/nav-panel/lib/nav-view.coffee:270:12)
    at HTMLLIElement.<anonymous> (/Users/christian_butzke/.atom/packages/nav-panel/lib/nav-view.coffee:48:12)
    at HTMLDivElement.jQuery.event.dispatch (/Users/christian_butzke/.atom/packages/nav-panel/node_modules/jquery/dist/jquery.js:4737:27)
    at HTMLDivElement.elemData.handle (/Users/christian_butzke/.atom/packages/nav-panel/node_modules/jquery/dist/jquery.js:4549:28)
```
### Commands

```
     -6:47.8.0 pane:show-previous-item (div.package-detail.panels-item)
  2x -6:45.8.0 find-and-replace:find-next (atom-text-editor.editor.is-focused)
     -6:43.9.0 find-and-replace:show (atom-text-editor.editor.is-focused)
  2x -6:42.9.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -6:41.7.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -6:41.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -6:38.5.0 find-and-replace:find-next (atom-text-editor.editor.mini.is-focused)
     -0:24.3.0 pane:show-next-item (atom-text-editor.editor.is-focused)
     -0:15.3.0 pane:show-previous-item (div.package-detail.panels-item)
```
### Config

``` json
{
  "nav-panel": {}
}
```
### Installed Packages

``` coffee
# User
atom-cli-diff, v1.3.0 (active)
atom-typescript, v10.1.6 (active)
git-plus, v5.16.2 (inactive)
language-elixir, v0.16.0 (active)
language-groovy, v0.6.0 (active)
language-haml, v0.24.0 (active)
language-lua, v0.9.11 (active)
language-nginx, v0.6.1 (active)
language-slim, v0.5.0 (active)
language-varnish, v0.5.0 (active)
line-diff-details, v1.3.5 (active)
linter, v1.11.16 (active)
nav-panel, v0.0.11 (active)
project-manager, v2.9.7 (active)
sort-lines, v0.14.0 (inactive)
Sublime-Style-Column-Selection, v1.7.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (inactive)
atom-light-ui, v0.44.0 (inactive)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (active)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (active)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.241.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by piotrazsko** [comment]
This problem

temporarily solved by removing line  270  in
atom-nav-panel/lib/nav-view.coffee
