### ISSUE TITLE
The nav-bar is not lniking to the location of the clicked on function, class, or method.

### ISSUE THREAD

**Issue by pjkaufman** [Ziink/atom-nav-panel#57]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package 0.0.11

### Stack Trace

Uncaught TypeError: Invalid Point: ((34, 0), 0)

```
At C:\Users\topse\AppData\Local\atom\app-1.18.0\resources\app\node_modules\text-buffer\lib\point.js:63

TypeError: Invalid Point: ((34, 0), 0)
    at Function.module.exports.Point.assertValid (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/point.js:63:21)
    at TextBuffer.module.exports.TextBuffer.clipPosition (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextBuffer.module.exports.TextBuffer.clipRange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/text-buffer.js:1071:26)
    at DisplayLayer.destroyFoldsIntersectingBufferRange (~/AppData/Local/atom/app-1.18.0/resources/app/node_modules/text-buffer/lib/display-layer.js:235:44)
    at TextEditor.module.exports.TextEditor.unfoldBufferRow (~/AppData/Local/atom/app-1.18.0/resources/app/src/text-editor.js:3086:38)
    at NavView.module.exports.NavView.gotoMarker (/packages/nav-panel/lib/nav-view.coffee:270:12)
    at /packages/nav-panel/lib/nav-view.coffee:48:12)
    at HTMLDivElement.dispatch (/packages/sass-autocompile/node_modules/jquery/dist/jquery.js:4435:9)
    at HTMLDivElement.elemData.handle (/packages/sass-autocompile/node_modules/jquery/dist/jquery.js:4121:28)
```

### Commands

```
  5x -5:34 core:move-down (input#sass-autocompile.compileCompact.input-checkbox)
     -5:06.3.0 core:backspace (input.hidden-input)
     -5:06.1.0 core:delete (input.hidden-input)
 68x -4:58.7.0 core:move-down (div.package-detail.panels-item)
 70x -3:51 core:move-up (div.package-detail.panels-item)
  4x -3:39.9.0 core:backspace (input.hidden-input)
  3x -3:29.4.0 core:move-down (input#sass-autocompile.directlyJumpToError.input-checkbox)
  3x -3:26.6.0 core:move-up (input#sass-autocompile.directlyJumpToError.input-checkbox)
 27x -3:20.5.0 core:move-down (input#sass-autocompile.directlyJumpToError.input-checkbox)
 55x -3:03.4.0 core:move-up (input#sass-autocompile.directlyJumpToError.input-checkbox)
 57x -1:57.2.0 core:move-down (input#sass-autocompile.compileOnSave.input-checkbox)
     -1:42.7.0 core:move-up (input.hidden-input)
 63x -1:41.8.0 core:move-down (input.hidden-input)
     -1:10.1.0 core:confirm (input.hidden-input)
  6x -1:03.7.0 core:backspace (input.hidden-input)
     -1:00.7.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
busy-signal 1.4.3 
intentions 1.1.2 
linter 2.2.0 
linter-php 1.3.2 
linter-sass-lint 1.7.4 
linter-ui-default 1.6.3 
minimap 4.29.2 
nav-panel 0.0.11 
remember-folds 0.3.0 
sass-autocompile 0.13.3 
```

**Comment by pjkaufman** [comment]
This issue has been resolved by one of the pull requests that are waiting to be merged (#38);
