### ISSUE TITLE
Uncaught TypeError: Cannot read property 'shadowRoot' of undefined

### ISSUE THREAD

**Issue by shibekin69** [Ziink/atom-nav-panel#58]
[Enter steps to reproduce:]

1. Was just opening a file.

**Atom**: 1.19.0 ia32
**Electron**: 1.6.9
**OS**: Microsoft Windows 8.1 Single Language
**Thrown From**: [nav-panel](https://github.com/Ziink/atom-nav-panel) package 0.0.11

### Stack Trace

Uncaught TypeError: Cannot read property 'shadowRoot' of undefined

```
At /C:/Users/USERNAME/.atom/packages/nav-panel/lib/nav-view.coffee:127

TypeError: Cannot read property 'shadowRoot' of undefined
    at NavView.module.exports.NavView.setFile (/packages/nav-panel/lib/nav-view.coffee:98:47)
    at /packages/nav-panel/lib/nav-panel.coffee:65:16
    at Function.module.exports.Emitter.simpleDispatch (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (~/AppData/Local/atom/app-1.19.0/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at ~/AppData/Local/atom/app-1.19.0/resources/app/src/workspace.js:551:30
```

### Commands

```
  4x -2:07.2.0 editor:move-to-beginning-of-word (input.hidden-input)
 18x -1:54.3.0 core:move-right (input.hidden-input)
     -1:45.8.0 core:move-up (input.hidden-input)
     -1:45.6.0 core:move-right (input.hidden-input)
     -1:45.3.0 core:move-down (input.hidden-input)
     -1:45 core:move-right (input.hidden-input)
  3x -1:38.8.0 editor:move-to-end-of-word (input.hidden-input)
     -1:38.1.0 editor:move-to-beginning-of-word (input.hidden-input)
  2x -1:37.5.0 editor:move-to-end-of-word (input.hidden-input)
     -1:36.6.0 core:move-right (input.hidden-input)
     -1:34.7.0 core:save (input.hidden-input)
     -1:31.3.0 editor:select-to-beginning-of-word (input.hidden-input)
     -1:30.9.0 core:move-left (input.hidden-input)
     -1:30.6.0 core:backspace (input.hidden-input)
     -1:29.8.0 core:save (input.hidden-input)
     -0:17.7.0 core:close (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.1.10 
atom-minify 0.8.0 
atom-typescript 11.0.6 
bookmark-panel 1.0.0 
color-picker 2.2.5 
diagrams 0.26.4 
highlight-selected 0.13.1 
hyperlink-hyperclick 1.3.4 
language-hjson 0.3.0 
minimap 4.29.3 
minimap-bookmarks 0.4.2 
minimap-codeglance 0.4.7 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-hide 0.3.0 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
minimap-selection 4.4.0 
minimap-split-diff 0.3.7 
nav-panel 0.0.11 
pretty-json 1.6.4 
sort-lines 0.14.0 
sorter 1.1.0 
split-diff 1.4.3 
styles-highlighter 2.3.0 
```

**Comment by shibekin69** [comment]
I think I fixed this by changing:

    gutter = $('.gutter-container', editorView.shadowRoot)

to...

    gutter = $('.gutter-container', editorView)
